//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liemie
{
    using System;
    using System.Collections.Generic;
    
    public partial class convalescence
    {
        public int id_patient { get; set; }
        public int id_lieux { get; set; }
        public System.DateTime date_deb { get; set; }
        public Nullable<System.DateTime> date_fin { get; set; }
        public string chambre { get; set; }
        public string tel_directe { get; set; }
    
        public virtual patient patient { get; set; }
        public virtual lieu_convalescence lieu_convalescence { get; set; }
    }
}
