//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liemie
{
    using System;
    using System.Collections.Generic;
    
    public partial class lieu_convalescence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lieu_convalescence()
        {
            this.convalescence = new HashSet<convalescence>();
        }
    
        public int id { get; set; }
        public string titre { get; set; }
        public string ad1 { get; set; }
        public string ad2 { get; set; }
        public string cp { get; set; }
        public string ville { get; set; }
        public string tel_fixe { get; set; }
        public Nullable<int> contact { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<convalescence> convalescence { get; set; }
        public virtual personne personne { get; set; }
    }
}
