//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liemie
{
    using System;
    using System.Collections.Generic;
    
    public partial class personne
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personne()
        {
            this.lieu_convalescence = new HashSet<lieu_convalescence>();
            this.patient1 = new HashSet<patient>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string sexe { get; set; }
        public Nullable<System.DateTime> date_naiss { get; set; }
        public Nullable<System.DateTime> date_deces { get; set; }
        public string ad1 { get; set; }
        public string ad2 { get; set; }
        public Nullable<int> cp { get; set; }
        public string ville { get; set; }
        public string tel_fixe { get; set; }
        public string tel_port { get; set; }
        public string mail { get; set; }
    
        public virtual infirmiere infirmiere { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lieu_convalescence> lieu_convalescence { get; set; }
        public virtual patient patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<patient> patient1 { get; set; }
        public virtual personne_login personne_login { get; set; }
    }
}
