//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liemie
{
    using System;
    using System.Collections.Generic;
    
    public partial class type_soins
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public type_soins()
        {
            this.soins = new HashSet<soins>();
            this.infirmiere = new HashSet<infirmiere>();
        }
    
        public int id_categ_soins { get; set; }
        public int id_type_soins { get; set; }
        public string libel { get; set; }
        public string description { get; set; }
    
        public virtual categ_soins categ_soins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<soins> soins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infirmiere> infirmiere { get; set; }
    }
}
