//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liemie
{
    using System;
    using System.Collections.Generic;
    
    public partial class visite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public visite()
        {
            this.soins_visite = new HashSet<soins_visite>();
        }
    
        public int id { get; set; }
        public int patient { get; set; }
        public int infirmiere { get; set; }
        public System.DateTime date_prevue { get; set; }
        public Nullable<System.DateTime> date_reelle { get; set; }
        public int duree { get; set; }
        public string compte_rendu_infirmiere { get; set; }
        public string compte_rendu_patient { get; set; }
    
        public virtual infirmiere infirmiere1 { get; set; }
        public virtual patient patient1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<soins_visite> soins_visite { get; set; }
    }
}
